spring.application.name=ecommerce
spring.datasource.url=jdbc:h2:file:./data/bodypaint
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
server.port=8081
mercadopago.access-token=APP_USR-8768122864744657-052818-49674bd93fa8ec7b0e1a02c32b7f9044-3434682798
